# This workflow will build the packages and upload to Github and PyPI

name: Publish
on: push
permissions:
  contents: read
jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build dist packages
        run: hatch build
      - name: Upload dist packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/aerospike-flask-cache
    steps:
    - name: Download dist packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-dist
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download dist packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-dist
        path: dist/
    - name: Release to Github
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/aerospike_flask_cache-*.tar.gz"
        body: "Source"
        draft: true
